[features]
seeds = false
skip-lint = false
[programs.localnet]
packers_and_movers = "GDazepq9rJxEZmi3DR3k1ZcmAwUvQm5dmcf6atWPFumq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
